import { Router, type IRouter } from "express";
import publicStoreRouter from "./public-store";
import healthRouter from "./health";
import authRouter from "./auth";
import branchesRouter from "./branches";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import suppliersRouter from "./suppliers";
import customersRouter from "./customers";
import salesRouter from "./sales";
import purchasesRouter from "./purchases";
import inventoryRouter from "./inventory";
import tasksRouter from "./tasks";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import rolesRouter from "./roles";
import expensesRouter from "./expenses";
import adminRouter from "./admin";
import platformRouter from "./platform";
import registerRouter from "./register";
import reportsRouter from "./reports";
import supportTicketsRouter from "./support-tickets";
import orderRequestsRouter from "./order-requests";
import activityLogsRouter from "./activity-logs";
import customerOrdersRouter from "./customer-orders";
import settingsOrderPageRouter from "./settings-order-page";
import settingsRouter from "./settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/public", publicStoreRouter);
router.use("/auth", authRouter);
router.use("/stores/register", registerRouter);
router.use("/branches", branchesRouter);
router.use("/categories", categoriesRouter);
router.use("/products", productsRouter);
router.use("/suppliers", suppliersRouter);
router.use("/customers", customersRouter);
router.use("/sales", salesRouter);
router.use("/purchase-orders", purchasesRouter);
router.use("/inventory", inventoryRouter);
router.use("/tasks", tasksRouter);
router.use("/users", usersRouter);
router.use("/dashboard", dashboardRouter);
router.use("/roles", rolesRouter);
router.use("/expenses", expensesRouter);
router.use("/admin", adminRouter);
router.use("/platform", platformRouter);
router.use("/reports", reportsRouter);
router.use("/support-tickets", supportTicketsRouter);
router.use("/order-requests", orderRequestsRouter);
router.use("/activity-logs", activityLogsRouter);
router.use("/customer-orders", customerOrdersRouter);
router.use("/settings/order-page", settingsOrderPageRouter);
router.use("/settings/store", settingsRouter);

export default router;
